package com.himanshoe.tracey.export

import com.himanshoe.tracey.model.InteractionEvent
import com.himanshoe.tracey.model.ReplayPayload

/**
 * Converts a [ReplayPayload] into a valid Compose UI test written as a plain
 * Kotlin string. The output pastes directly into an `androidTest` source set
 * and runs without modification.
 *
 * The generated test uses `ComposeTestRule` and produces:
 * - `performClick` for [InteractionEvent.Click]
 * - `performTouchInput { longClick() }` for [InteractionEvent.LongPress]
 * - `performScrollBy` for [InteractionEvent.Scroll]
 * - `performTouchInput { swipe() }` for [InteractionEvent.Swipe]
 * - `performTouchInput { pinch() }` for [InteractionEvent.Pinch]
 * - `waitForIdle` after every action
 *
 * Each action is preceded by a descriptive comment indicating what the user
 * was doing, the composable path, and the timestamp relative to session start.
 *
 * Usage:
 * ```kotlin
 * val testCode: String = TestCaseExporter.export(payload)
 * // Write to a file, copy to clipboard, attach to a bug report, etc.
 * ```
 */
object TestCaseExporter {

    /**
     * Generates a complete, runnable Compose UI test from [payload].
     *
     * @param payload The replay to convert. All events in [ReplayPayload.events]
     *                are translated into test actions in order.
     * @param testClassName The name of the generated test class. Defaults to
     *                      `"TraceyGeneratedTest"`.
     * @param testFunctionName The name of the generated test function. Defaults to
     *                         `"replayInteractions"`.
     * @return A Kotlin source string containing a complete test class.
     */
    fun export(
        payload: ReplayPayload,
        testClassName: String = "TraceyGeneratedTest",
        testFunctionName: String = "replayInteractions",
    ): String {
        val baseTimestamp = payload.events.firstOrNull()?.timestampMs ?: 0L

        return buildString {
            appendLine(fileHeader(payload))
            appendLine()
            appendLine("class $testClassName {")
            appendLine()
            appendLine("    @get:Rule")
            appendLine("    val composeTestRule = createComposeRule()")
            appendLine()
            appendLine("    @Test")
            appendLine("    fun $testFunctionName() {")
            appendLine("        // Session: ${payload.sessionId}")
            appendLine("        // Captured: ${formatTimestamp(payload.capturedAtMs)}")
            appendLine("        // Device: ${payload.deviceInfo.model} (${payload.deviceInfo.platform})")
            appendLine("        // App: ${payload.appVersion}")
            if (payload.isCrashPayload) {
                appendLine("        // Crash: ${payload.crashReason}")
            }
            appendLine()

            payload.events.forEach { event ->
                val relativeMs = event.timestampMs - baseTimestamp
                append(eventToTestCode(event, relativeMs))
                appendLine("        composeTestRule.waitForIdle()")
                appendLine()
            }

            appendLine("    }")
            appendLine("}")
        }
    }

    private fun fileHeader(payload: ReplayPayload) = buildString {
        appendLine("// Generated by Tracey — do not edit manually.")
        appendLine("// Session  : ${payload.sessionId}")
        appendLine("// Duration : ${payload.durationMs}ms")
        appendLine("// Events   : ${payload.events.size}")
        appendLine()
        appendLine("package com.example.test")
        appendLine()
        appendLine("import androidx.compose.ui.test.junit4.createComposeRule")
        appendLine("import androidx.compose.ui.test.onNodeWithTag")
        appendLine("import androidx.compose.ui.test.performClick")
        appendLine("import androidx.compose.ui.test.performScrollBy")
        appendLine("import androidx.compose.ui.test.performTouchInput")
        appendLine("import androidx.compose.ui.test.swipe")
        appendLine("import androidx.compose.ui.test.longClick")
        appendLine("import androidx.compose.ui.test.pinch")
        appendLine("import androidx.compose.ui.geometry.Offset")
        appendLine("import org.junit.Rule")
        appendLine("import org.junit.Test")
    }

    private fun eventToTestCode(event: InteractionEvent, relativeMs: Long): String = buildString {
        val time = formatRelativeTime(relativeMs)

        when (event) {
            is InteractionEvent.Click -> {
                appendLine("        // [$time] User clicked at (${event.x.fmt()}, ${event.y.fmt()})")
                appendLine("        // Path: ${event.path}")
                val tag = leafTag(event.path)
                if (tag != null) {
                    appendLine("        composeTestRule.onNodeWithTag(\"$tag\").performClick()")
                } else {
                    appendLine("        composeTestRule.onRoot().performTouchInput {")
                    appendLine("            click(Offset(${event.x.fmt()}f, ${event.y.fmt()}f))")
                    appendLine("        }")
                }
            }

            is InteractionEvent.LongPress -> {
                appendLine("        // [$time] User long-pressed at (${event.x.fmt()}, ${event.y.fmt()}) for ${event.holdDurationMs}ms")
                appendLine("        // Path: ${event.path}")
                val tag = leafTag(event.path)
                if (tag != null) {
                    appendLine("        composeTestRule.onNodeWithTag(\"$tag\").performTouchInput {")
                    appendLine("            longClick()")
                    appendLine("        }")
                } else {
                    appendLine("        composeTestRule.onRoot().performTouchInput {")
                    appendLine("            longClick(Offset(${event.x.fmt()}f, ${event.y.fmt()}f))")
                    appendLine("        }")
                }
            }

            is InteractionEvent.Scroll -> {
                appendLine("        // [$time] User scrolled (Δx=${event.deltaX.fmt()}, Δy=${event.deltaY.fmt()})")
                appendLine("        // Path: ${event.path}")
                val tag = leafTag(event.path)
                if (tag != null) {
                    appendLine("        composeTestRule.onNodeWithTag(\"$tag\")")
                    appendLine("            .performScrollBy(x = ${event.deltaX.fmt()}f, y = ${event.deltaY.fmt()}f)")
                } else {
                    appendLine("        composeTestRule.onRoot()")
                    appendLine("            .performScrollBy(x = ${event.deltaX.fmt()}f, y = ${event.deltaY.fmt()}f)")
                }
            }

            is InteractionEvent.Swipe -> {
                appendLine("        // [$time] User swiped from (${event.startX.fmt()}, ${event.startY.fmt()}) to (${event.endX.fmt()}, ${event.endY.fmt()})")
                appendLine("        // Path: ${event.path}")
                appendLine("        composeTestRule.onRoot().performTouchInput {")
                appendLine("            swipe(")
                appendLine("                start = Offset(${event.startX.fmt()}f, ${event.startY.fmt()}f),")
                appendLine("                end   = Offset(${event.endX.fmt()}f, ${event.endY.fmt()}f),")
                appendLine("            )")
                appendLine("        }")
            }

            is InteractionEvent.Pinch -> {
                appendLine("        // [$time] User pinched (zoom=${event.zoomDelta.fmt()}, rotation=${event.rotationDelta.fmt()}°)")
                appendLine("        // Path: ${event.path}")
                appendLine("        composeTestRule.onRoot().performTouchInput {")
                appendLine("            pinch(")
                appendLine("                start0 = Offset(${(event.centroidX - 100f).fmt()}f, ${event.centroidY.fmt()}f),")
                appendLine("                end0   = Offset(${(event.centroidX - 100f * event.zoomDelta).fmt()}f, ${event.centroidY.fmt()}f),")
                appendLine("                start1 = Offset(${(event.centroidX + 100f).fmt()}f, ${event.centroidY.fmt()}f),")
                appendLine("                end1   = Offset(${(event.centroidX + 100f * event.zoomDelta).fmt()}f, ${event.centroidY.fmt()}f),")
                appendLine("            )")
                appendLine("        }")
            }

            else -> { /* lifecycle/screen events — no UI action generated */ }
        }
    }

    private fun leafTag(path: String): String? {
        val leaf = path.split(" > ").lastOrNull()?.trim() ?: return null
        if (leaf.startsWith("Screen[")) return null
        return leaf
    }

    private fun Float.fmt(): String {
        val intPart = toInt()
        val fracPart = ((kotlin.math.abs(this) * 10).toInt() % 10)
        return "$intPart.$fracPart"
    }

    private fun formatRelativeTime(ms: Long): String {
        val seconds = ms / 1000
        val millis = ms % 1000
        val minutes = seconds / 60
        val secs = seconds % 60
        return "${minutes.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}.${millis.toString().padStart(3, '0')}"
    }

    private fun formatTimestamp(epochMs: Long): String {
        val seconds = epochMs / 1000
        return "epoch+${seconds}s"
    }
}
